### ISSUE TITLE
Don't show (Twitch) channels which are only hosting as being Live.

### ISSUE THREAD

**Issue by Nhoise** [freaktechnik/justintv-stream-notifications#100]
I don't remember this add-on doing that before the 3.0.1 update.

**Comment by freaktechnik** [comment]
Yes, it's an addition with 3.0.1. I'm not sure if the preference to disable hosting is in the version published, or if that'll be in the next one. To change the pref, see http://jtvn.humanoids.be/aboutconfig/

**Comment by Nhoise** [comment]
I don't see any options for it in about:config with 3.0.1, but if it's coming in a later update that's perfectly fine with me. It's not a major annoyance by any stretch.

**Comment by freaktechnik** [comment]
Okay, so I'll leave this open until the next version.

**Comment by Nhoise** [comment]
Perfect, really liking the new interface and all by the way.
Your add-on is def the slickest of all the ones i tried, kudo's.

**Comment by freaktechnik** [comment]
Thanks!

**Comment by freaktechnik** [comment]
3.1.1 is out now, so the pref is available.
