### ISSUE TITLE
(Twitch) Channels won't update status if they host someone after they stop their own stream.

### ISSUE THREAD

**Issue by Nhoise** [freaktechnik/justintv-stream-notifications#101]
As title says.

I was watching someone stream and after it ended they hosted someone elses.
This is causing the notifier to not wanting to change the channel status, even after manually refreshing a couple of times..
It keeps displaying the channel as being Live with the game they played last.

* Using minimal display style style.
* Firefox 39.0 + 3.0.1

**Comment by freaktechnik** [comment]
You don't get a title change notification? There is no dedicated hosting notification, or offline notification for streams going into host mode.

**Comment by Nhoise** [comment]
It wasn't updating the status when a streamer went from being 'Live' to 'offline and hosting someone'.
The notifier kept displaying the person as being Live himself.

But I did a quick full reinstall yesterday because i might have broke something when i tried to disable the hosting feature myself by digging through the code. (Even though i undid all chances i made after i didn't succeed lol)
It seems to be behaving now though, but I'll keep an eye on it.

**Comment by freaktechnik** [comment]
Oh, if the hosted channel is offline, it will still change the name of the channel in the current release. This will be fixed in 3.1.

**Comment by Nhoise** [comment]
Yeah, this is a non-issue probably caused by something i messed up. I'll close it.
