### ISSUE TITLE
Icon won't show up in FF42.0 portable (3.2.0.9999-pre)

### ISSUE THREAD

**Issue by Nhoise** [freaktechnik/justintv-stream-notifications#115]
My main firefox is on 41.0.2 so i installed your pre-release in my portable version, which is beta42.0
But the icon won't shop up. If i delete it and install the regular 3.1.1 everything is fine, but when i install the pre-release the icon disappears instantly.

3.2.0.7480f3c-alpha seems to work fine as well, but has no livestreamer support yet (as far as i could see). Which is what i was going to test.

**Comment by freaktechnik** [comment]
The 9999 version has livestreamer support, which should be just above the 7480.

As far as icon goes, I changed the build procedure, so I'll look into that

**Comment by Nhoise** [comment]
I can't open the Channel manager either, via the add-on options. So it's not just the icon which is having trouble.

**Comment by freaktechnik** [comment]
Could you open the Browser Console and see if there's any error there? (big, red and long, because there's a trace normally)

**Comment by Nhoise** [comment]
justintv-stream-notifications:Object { , 5 more… } runner.js:164
justintv-stream-notifications:Object { , 5 more… } Promise-backend.js:937

> message:"Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsILocalFile.initWithPath]"

>stack:"@undefined:31:NaN
MozFile@resource://gre/modules/commonjs/sdk/io/file.js:31:3
exists@resource://gre/modules/commonjs/sdk/io/file.js:68:10
updatePath@resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/livestreamer.js:57:35
@resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/livestreamer.js:69:1
@resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/listview.js:22:22
@resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/main.js:14:22
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:747:1
"

Anything useful?

**Comment by freaktechnik** [comment]
does the livestreamer path pref have a string in it?

**Comment by Nhoise** [comment]
No, it's empty.

**Comment by freaktechnik** [comment]
Okay, setting it to the path to your livestreamer.exe would fix it. I'll have to look into why it's throwing an error, though.

**Comment by Nhoise** [comment]
I'll set the path and see what it does next.

**Comment by Nhoise** [comment]
Nevermind, i forgot to include the livestreamer.exe in the path

Got it working. :+1:

**Comment by Nhoise** [comment]
I have medium set as preferred quality, but when trying to open a stream which doesn't have medium available it shuts down the CMD without starting livestreamer.
Would it be possible to have a fallback option enabled?

**Comment by freaktechnik** [comment]
Oh, I didn't know about `--default-stream`. I'll set it to best.
So the icon is still now showing?

**Comment by Nhoise** [comment]
Yes, everything is working great.
Forcing to always open with livestreamer works, as well as right click - open with livestreamer.

Pretty interesting you added the explore tab as well. How does it decide which channels to display there?
Is it based on anything or just does it take whatever from the twitch front page?

**Comment by freaktechnik** [comment]
It takes featured channels from the API of each provider that is supported. So it's probably equal to the twitch frontpage for twitch.

**Comment by freaktechnik** [comment]
Okay, so default-stream only does something if the field is left empty. I don't currently have a way of detecting when livestreamer failed
