### ISSUE TITLE
Channels opened from Explore default to open with livestreamer

### ISSUE THREAD

**Issue by Nhoise** [freaktechnik/justintv-stream-notifications#116]
Double checked if 'Always use livestreamer' isn't checked, it isn't.
It happens on all 3 sections. Twitch, Hitbox and youtube. All default open with livestreamer.

I'm guessing this isn't on purpose?

**Comment by Nhoise** [comment]
Another things is that having medium in the livestreamer quality messes with both Youtube and Hitbox, as those don't have medium available as quality options.
Would it be possible to add the ability to add different fallback options for different platforms?
Like 480p for Hitbox, 720p for youtube? Or is that too difficult/impossible to implement?

**Comment by freaktechnik** [comment]
That's just not info I currently have.

**Comment by freaktechnik** [comment]
(but feel free to open an issue on the quality preset thing, and I'll tag it as enhancement.)

**Comment by Nhoise** [comment]
Will do
