### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Kylllyk** [freaktechnik/justintv-stream-notifications#138]
Hello,

It would be nice to have the ability to choose a dark theme for the list of streams. 

Thanks.

**Comment by freaktechnik** [comment]
It should in the default state (no hover) use the background and teyt color supplied by your theme. Though it's possible it uses the default values for websites insted, I'd have to double check. Essentially it is not "light" atm, however I will think about adding the possibility to choose a base style that's preset by the extension and not the browser.

Thanks for the suggestion!

**Comment by freaktechnik** [comment]
Good news! I've been reworking the css a little and now have the easy possibility to change the base colors. I expect to have a dark and a black (with reduced text contrast) theme in the next release.

**Comment by freaktechnik** [comment]
I just released a beta version that adds the dark theme: https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/?page=1#version-3.3.0-pre7

It's not well-tested yet, so it might loose your data upon upgrade.
