### ISSUE TITLE
Option for Disabling Hosting Notifications

### ISSUE THREAD

**Issue by DominickLR** [freaktechnik/justintv-stream-notifications#139]
Sometimes my subscribed channels on Twitch host other channels that I'm not interested in. I'd only like to receive notifications for when the channel starts streaming.

**Comment by freaktechnik** [comment]
But you'd still like to see hosted channels in the panel?

**Comment by DominickLR** [comment]
>But you'd still like to see hosted channels in the panel?

No, if possible I'd only like to get notified when the channel starts streaming. Maybe this could be configurable in the settings, such as: "Get notified when this channel hosts another channel".

**Comment by DominickLR** [comment]
Whoops, accidentally hit the "close issue" button.

**Comment by freaktechnik** [comment]
I think disabling hosting info at all might be the solution for you. Until #110 is fixed, there is a hidden pref for it, as explained on http://streamnotifier.ch/aboutconfig. Just double click it to toggle the value.

**Comment by DominickLR** [comment]
>I think disabling hosting info at all might be the solution for you. Until #110 is fixed, there is a hidden pref for it, as explained on http://streamnotifier.ch/aboutconfig. Just double click it to toggle the value.

Okay, thank you. I disabled it in *about:settings* and I no longer receive hosting notifications.
