### ISSUE TITLE
Conflicting with HTTPS everywhere by EFF

### ISSUE THREAD

**Issue by LeLobster** [freaktechnik/justintv-stream-notifications#143]
Twitch thumbnails in the Online/Offline tab don't show on startup, while thumbs in the Discover tab show just fine.
After i disable/enable your extension Online/Offline channel thumbs show up again.
Can't add Youtube channels to the list.

## System Info

 - *Operating System*: Win7
 - *Firefox Version*: 44.0.2
 - *Extension Version*: 3.2.3-pre1
 - *HTTPS Everywhere version*: 5.1.4 with Observatory disabled.  
https://github.com/EFForg/https-everywhere/issues/  
https://www.eff.org/https-everywhere

**Comment by freaktechnik** [comment]
You don't need any link, all you need is a channel that actually has a slug name. I'm still looking into also supporting adding channels by ID. I've tried to explain it under http://streamnotifier.ch/help/channels-manager/#youtube.

So if you wanted to add https://www.youtube.com/user/google you'd just enter "google" into the username field.

**Comment by Nhoise** [comment]
Ok, take this channel for example.
https://youtube.com/user/JamesNintendoNerd

[JamesNintendoNerd doesn't work(https://i.imgur.com/f74bTHw.gifv)
The channel alias Cinemassacre doesn't work either. That's why I figured i'd try out the links because the simple names didn't work.

**Comment by freaktechnik** [comment]
JamesNintendoNerd works perfectly fine for me: 
![screenshot from 2016-02-29 18 33 18](https://cloud.githubusercontent.com/assets/640949/13402953/f26a827e-df12-11e5-88d1-ddf402460544.png)

**Comment by Nhoise** [comment]
Hmm, i just whipped out my FF 45beta and indeed it added just fine. (unimportant side note: I'm not seeing requests like yours show up in the console though)
I think i have a conflicting extension installed. I suspected uMatrix to be it but after i disabled it i still couldn't add anything Youtube.

Here i go disabling everything i have installed and enabling one by one (damn you FF for not having an easier way to debug conflicting extension) unless you have any other suggestions?

**Comment by freaktechnik** [comment]
You can get those requests showing in the browser console in two ways:
 1. Enable XHR logging under Net, it will at least show the base URL when something is loaded.
 2. Set the logLevel to "all", where that pref is is described on http://streamnotifier.ch/aboutconfig

**Comment by Nhoise** [comment]
XHR logging is enabled but nothing is showing in the console.
Only thing it will show are links to the already added Twitch channel images from static-cdn.jtvnw.net on reload of the manager.

**Comment by freaktechnik** [comment]
Then something is indeed blocking the request. If it wasn't something external doing it you should see the error printed in the browser console by default, which I assume you'd have reported (only logging is not shown by default).

**Comment by Nhoise** [comment]
I already knew i had something messed up in this browser because every time i start it [this is how the notification window looks](https://i.imgur.com/JK6xOW2.png)
As you can see the thumbnails don't show, if i go in the extension window and disable/enable your addon everything goes back to normal.
Apparently I've now figured out it goes a bit further than just thumbnails not showing on first launch.
I'm gonna go ahead and disable a bunch of addons and troubleshoot a bit

**Comment by Nhoise** [comment]
https://www.eff.org/https-everywhere
is the culprit.

I don't see how this can happen though, all that extension is doing is forcing https where it can.
I'm not blocking http requests, and it's not doing anything funky at all as far as i know

**Comment by freaktechnik** [comment]
Especially since youtube API requests should already be https. I'll take a look at it later, but it's most likely not my fault, since I just use the default Request method from the Add-on SDK. That doesn't mean I don't want it to be resolved.

**Comment by Nhoise** [comment]
> Especially since youtube API requests should already be https.

Exactly.
[But the strange this is that it also blocks the thumbnails from showing the notification window of your extension.](https://i.imgur.com/JK6xOW2.png) As this is completely unrelated to youtube/google.
I have to disable/enable your extension for it to work like normal. **And this is also because of HTTPS Everywhere.**

**Comment by Nhoise** [comment]
I've just set HTTPS Everywhere to be disabled on both Google API and Twitch, but on restart it doesn't change anything.
Guess HTTPS is doing something really fucky behind the scenes.

I'm pretty sure though this didn't happen in the past, and i've had HTTPS running long before i installed your extension.
So either it's something that changed in one of the HTTPS updates after 5.1.1/5.1.2 or something that changed in your extension with one of the latest updates.
I really can't remember when this conflict first started showing.

**Comment by Nhoise** [comment]
Just installed HTTPS everywhere 5.1.4 in my FF45beta and none of the issue i have on FF44.0.2 show up. I can see all the thumbnails and i can add youtube channels.
I really don't know what's going on.

**Comment by LeLobster** [comment]
Do you want me to close this? It's more something to do with my specific browser and settings than your extension.

**Comment by freaktechnik** [comment]
I'm not sure yet and havent had time to look into it yet and probably will only have starting next week. I'll close it once I give up trying to find what went wrong ir found it ;)

**Comment by LeLobster** [comment]
Either one your updates fixed this or the newest HTTPS Everywhere update did, but I noticed I'm not having the 'thumbnail not showing' problem anymore.
