### ISSUE TITLE
Replace open with Livestreamer with Copy Channel URL

### ISSUE THREAD

**Issue by freaktechnik** [freaktechnik/justintv-stream-notifications#159]
Harmonizes the extension with Twitch TOS and simplifies WebExt transition.

**Comment by freaktechnik** [comment]
Add an option to define a pattern in which the url should be embedded. This lets people still use livestreamer relatively easy while not explicitly promoting it.

**Comment by LeLobster** [comment]
I know I'm late to the party but why did you exactly remove Livestreamer support? Is it against their TOS because it doesn't show advertisements?

**Comment by freaktechnik** [comment]
It is against the TOS because it plays twitch streams without using their official player.

However the deeper reasoning is, that with WebExtensions such a feature would require a dedicated binary on the user's system just to launch Livestreamer. I do not want to maintain such a binary for all platforms and also don't think users should trust me with such a binary. I'm sure there will still be extensions that will support direct Livestreamer starting, but this approach seems to be the most common one, since it is not direct Livestreamer support.
