### ISSUE TITLE
shift + rightclick

### ISSUE THREAD

**Issue by klonamy** [freaktechnik/justintv-stream-notifications#185]
## Issue

The "shift + rightclick" does get me a new Window of Firefox with the following Url:
http://streamnotifier.ch/help/channels-manager/

## System Info

 - *Operating System*: Windows 10
 - *Firefox Version*: Firefox beta 49.0 + e10s enabled
 - *Extension Version*: 3.3.0-rc01

**Comment by freaktechnik** [comment]
It's only supposed to work with shift + left click. I have no intention of overriding any other key combination.

**Comment by klonamy** [comment]
oh sry was the leftclick xD

**Comment by freaktechnik** [comment]
So it works with shift + left click?

**Comment by klonamy** [comment]
no

**Comment by freaktechnik** [comment]
That's super weird. All I can assume is that shift would not count as modifier for some reason and thus the event not getting prevented.

Are you familiar with about:config and the Browser Console?

**Comment by klonamy** [comment]
Ich denke du brauchst nur den JS-Log?

- ReferenceError: Application is not defined
- Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="m" Modifikatoren="control,alt"browser.xul
- Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="n" Modifikatoren="accel, alt"browser.xul
- Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="t" Modifikatoren="accel,alt"browser.xul
- Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"

**Comment by klonamy** [comment]
justintv-stream-notifications:TypeError: Type does not implements method: patch@diffpatcher#l3r12pk9mig
Stack-Trace:
dispatch@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/method/core.js:116:24
foldp/output<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:212:32
map/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:61:65
transform/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:44:29
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
merges/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:194:31
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
lift/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:169:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
transform/next@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:37:24
filter/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:54:7
transform/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:44:29
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
InputPort.prototype.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/input/system.js:104:5

**Comment by freaktechnik** [comment]
Hmm, I'm not sure how any of those would be related. In theory the events are handled within the content so commonjs/sdk should not be involved.

**Comment by klonamy** [comment]
In the Test-Profile without any addons it is not even fireing an event.

**Comment by freaktechnik** [comment]
The event should be canceled by the listener on the page and then a command should be sent to the extension to collect and copy the debug data.

**Comment by freaktechnik** [comment]
Closing as worksforme. Not sure what's wrong here.
