### ISSUE TITLE
Quick access key for Copy Stream URL

### ISSUE THREAD

**Issue by Isiolith** [freaktechnik/justintv-stream-notifications#187]
Hello, 
Since the last update, a new feature was added on right click menu : "Copy Stream URL", witch works great.
For automation purpoises, would it be possible to have a shortcut underlined quick access key for this ? (I don't know the exact name of this feature in english).

For example for me in firefox, when I right click on a link, the contextual menu opens, and pressing the "C" key would instantly perform the action.

Thus the "C" key for "Copy Stream URL" would be nice.

**Comment by freaktechnik** [comment]
I am not sure that is currently possible, but I will certainly look into it!

**Comment by freaktechnik** [comment]
Currently the firefox platform doesn't support explicit keyboard shortcuts inside the context menu, you can however use your os navigation (so C is probably fine in English, or whatever it starts with in your language).

I will, however, look into creating a shortcut that doesn't require the context menu, but I can't guarantee anything.

**Comment by freaktechnik** [comment]
(This was implemented by doing the copy action when triggering a copy while a channel is focused (with the keyboard). An access key for the context panel is yet to be implemented, but since this is quicker to access I chose to resolve this)

**Comment by freaktechnik** [comment]
(This was implemented by doing the copy action when triggering a copy while a channel is focused (with the keyboard). An access key for the context panel is yet to be implemented, but since this is quicker to access I chose to resolve this)
