### ISSUE TITLE
Something about long stream-or game titles 

### ISSUE THREAD

**Issue by LeLobster** [freaktechnik/justintv-stream-notifications#192]
[Example of what I mean.](https://i.imgur.com/OOgypu7.png) Don't mind my custom CSS.
Using `normal` panel display with extra info enabled: sometimes when a streamer has a long stream title, or in rare cases where they're playing a game which has a long name, the text row gets cut off (as seen in example)

It's a small annoyance but it doesn't look right.
My suggestion would be to either truncate the titles to max-width of the panel or dynamically adjust the panel width to match text (if that's possible).
Let me know what you think.

**Comment by freaktechnik** [comment]
I think I should enable hyphenation for all text content in the panel, so the titles get broken up better, instead of just at word boundaries and dashes.

**Comment by freaktechnik** [comment]
I also want to mention that with the default panel width and text size this is way more common - almost every title gets split on two lines.

**Comment by LeLobster** [comment]
> default panel width

You mean the value of ...@jetpack.panel_minWidth?
I tried to increase that (like I have done with a past version) but it didn't have any effect so I figured the entry wasn't used anymore.

Still without my own CSS it looks [like this with long titles](https://i.imgur.com/0r9UZkJ.png)
I don't mind the titles being split over 2 lines but the extra info bit should at least be aligned with the others imo.

**Comment by freaktechnik** [comment]
it uses max width now, iirc.

I explicitly decided not to align it, since super long titles (i.e. 3+ lines) will then get split up over even more lines.

**Comment by LeLobster** [comment]
You know I'm talking about the viewers/game/provider part right? I don't see how that would give issues with titles because they're both separate parts of the panel?
With longer titles the `extra info` bit just gets pushed down below the avatar part.
Can't you just force it to always start at ?px from the left?

I tried to do that with my own CSS but couldn't get it to work.

**Comment by freaktechnik** [comment]
it is possible to do that, however if the title has three lines, then a line of the title also gets pushed down, which would then also make that line start earlier.

**Comment by LeLobster** [comment]
Hmm, yeah. Didn't think about that.

So it would be difficult to have it do something [like this?](https://i.imgur.com/lWjpsEx.png)
The whole area left of the red line is only avatar space with padding

**Comment by LeLobster** [comment]
I also just set `...@jetpack.panel_minWidth` to 640 and disabled/re-enabled the addon and now it did work.
Didn't think about it needing a restart after changing it, so yeah minwidth and maxheight both still work.
Looks a lot better in my case with width=640

**Comment by freaktechnik** [comment]
OH, there's another part to this. With the upcoming webextensionification of this extension the panel will no longer have a fixed size and instead resize much better to fit the content's size. This will potentially lead to the panel getting as wide as the titles get, which I'm not yet sure I want to allow on that scale.

**Comment by freaktechnik** [comment]
This will get vastly improved by #335

**Comment by freaktechnik** [comment]
I think this should be much better now and I am not aware of any other improvement I could still make.
