### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by wolstrom** [freaktechnik/justintv-stream-notifications#239]
When I do a right click on a channel, that's what happen. Is it normal or can it be fix ?
![live stream notifier](https://cloud.githubusercontent.com/assets/26373656/23844679/25883c34-07c4-11e7-9b62-1914e0458953.png)

**Comment by freaktechnik** [comment]
That's a bug and will eventually be fixed. You can work around it by first right clicking something in a tab.
