### ISSUE TITLE
scaling wrong on second monitor

### ISSUE THREAD

**Issue by Daisenki** [freaktechnik/justintv-stream-notifications#266]
- *Operating System*: W10 1703
 - *Firefox Version*: 53.0.3 (64-Bit)
 - *Extension Version*: 3.3.1

Wrong scaling on 1080p 100% 2nd monitor

![snip_20170601202416](https://cloud.githubusercontent.com/assets/22057956/26694814/02df3492-4709-11e7-9c73-10fa177eae87.jpg)

Right scaling on 4K 150% main monitor

![snip_20170601202501](https://cloud.githubusercontent.com/assets/22057956/26694807/fb530910-4708-11e7-8f56-f8081221781b.jpg)

Any ideas why? Can I do something?

**Comment by freaktechnik** [comment]
To my knowledge the scaling I do is always in CSS pixels, so independent of DPI. I fear this is a Firefox bug.

I wonder if this will also be the case with the webextebsion version (that should be available as beta very soon), since that uses entirely different resizing.

**Comment by Daisenki** [comment]
You mean the layout.css.devPixelsPerPx setting? Its on default and I test it with changing the setting but the issue is the same at my Firefox. 

Thanks for the info, then I'm waiting for the beta or a new Firefox version, the issue is not a big deal for me.

**Comment by freaktechnik** [comment]
Hi, the first beta is now available on https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/beta. It should in theory be essentially the same extension, just a little different (and yes, the panel is not fun if you have a few channels, but I'm not yet sure how to improve that).

**Comment by Daisenki** [comment]
Thanks for the info!

I'm now on pre3, the tabs are glitching on my second monitor, but not every time, it try's to fix the scaling...

![snip_20170618145549](https://user-images.githubusercontent.com/22057956/27260852-3bc32aae-5436-11e7-9ee8-4d115a17cce9.png)

![snip_20170618145352](https://user-images.githubusercontent.com/22057956/27260849-3087a8ae-5436-11e7-982a-63437ad69945.png)

The main desktop is still fine, only the second desktop because fucking W10 scaling.

**Comment by freaktechnik** [comment]
Thabk you for trying out the beta!

That sounds like a platform bug then. I'll try to find out if mozilla is aware of the issue and if not I'll open an issue for it with them and link it back here.

**Comment by Daisenki** [comment]
I have test a few things with your beta and layout.css.devPixelsPerPx, the default is -1 at my Firefox, with this setting I have this issue. When I set it to 1 I overwrite the scaling, but it only effect my main desktop Firefox (gets tiny), not my second monitor open Firefox, the issue is gone with your beta pre3.

**Comment by Daisenki** [comment]
The issue is fixed with your public update 3.4.0 it works now perfect on both monitors, the scaling is correct now! 

Thanks for the fix! :)

**Comment by freaktechnik** [comment]
That's super weird. It seems like it has trouble with the reflows from the images and text loading in. At least that's what I'd assume.

**Comment by Daisenki** [comment]
Something what you did at version 3.4.0 was right for the scaling, it runs now on the second monitor correct like it should and not like it was on my first comment with version 3.3.1. So its the right way I guess.

**Comment by Daisenki** [comment]
Hey,

I'm using now two monitors with 4k, no longer two different resolutions and scaling. The bug isn't anymore present on my side.

Did you want to work further on that bug or close the ticket? It seams not much to do anyway from your side because it's more a Mozilla problem.

**Comment by freaktechnik** [comment]
Since I moved it to done I probably wanted to close it. I remember reading about some bug around then, but I can't find it anymore...
