### ISSUE TITLE
indexedDB can't be opened without cookies

### ISSUE THREAD

**Issue by freaktechnik** [freaktechnik/justintv-stream-notifications#318]
Somehow the indexedDB never opens when cookies are disabled.

**Comment by freaktechnik** [comment]
Seems like this is a platform issue of Firefox I can't really do much about:
- https://github.com/openstyles/stylus/issues/152
- https://github.com/localForage/localForage/issues/501
- https://bugzilla.mozilla.org/show_bug.cgi?id=944918 seems to be kinda related
- there's also weird bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=781983 which seem to be wrong, since indexeddb doesn't work without cookies...

workaround: https://github.com/openstyles/stylus/issues/151#issuecomment-322047852

**Comment by Daisenki** [comment]
Heyho, the email was from me.

I found a new webextension cookie manager for FF57+ yesterday (https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/), so it's not necessary anymore for me to deactivate the cookies complete or use the crappy internal Firefox cookie control system. 

With Cookie Autodelete I can leave the cookies activated like I did before with Cookies Exterminator, and your addon works without problems in this case. 

In my opinion you can close it as Firefox bug, maybe Mozilla fix it with future versions.

**Comment by freaktechnik** [comment]
Yeah, I'm tracking all the private mode related storage issues either way and will bring that up eventually if it doesn't get fixed. Thanks for the patience!
