### ISSUE TITLE
Copy stream URL

### ISSUE THREAD

**Issue by olmium** [freaktechnik/justintv-stream-notifications#336]
When I copy the URL of a live channel I get "undefined" instead of the URL. But I get the URL for channels who are on non-live state.

## System Info

 - *Operating System*: [windows 10 64-bits]
 - *Firefox Version*: [55.0.3 64bits]
 - *Extension Version*: [3.5.0pre14]

**Comment by freaktechnik** [comment]
I think this applies to all internal channels but not to external channels.
