### ISSUE TITLE
Open streams through the streamlink

### ISSUE THREAD

**Issue by Silergo** [freaktechnik/justintv-stream-notifications#377]
There is only options to copy URL when you rightclicking the thumbnail. Is there any way to open stream using streamlink (livestreamer) instead?

**Comment by freaktechnik** [comment]
The only solution to this would be to have you install additional software, which is not something I want to provide.

**Comment by freaktechnik** [comment]
(looking into other solutions though: https://github.com/plneappl/streamlink-helper/issues/1 )

**Comment by Silergo** [comment]
How about this addon? https://github.com/IsSuEat/open-livestreamer-firefox-addon

**Comment by freaktechnik** [comment]
That doesn't seem to be migrated yet to support Firefox 57. The one I am (hopefully) going to integrate with is compatible with Firefox 57.

**Comment by freaktechnik** [comment]
Will integrate with streamlink-helper.
