### ISSUE TITLE
Couldn't load "USERNAME" for Twitch.

### ISSUE THREAD

**Issue by Dutchs** [freaktechnik/justintv-stream-notifications#458]
I get said error when adding a new user for twitch, user in this case being "dutchs"
Exact error message: "Couldn't load "dutchs" for Twitch. Please make sure you are using the correct username"
The user is added at this point but none of my following channels are added.
This was after a clean install of the extension.

## System Info

- *Operating System*: Win 10 (64-bit)
- *Firefox Version*: 64.0 (64-bit)
- *Extension Version*: 3.10.3

## Debug Dump

```json
{
  "channels": [],
  "users": [
    {
      "uname": "Dutchs",
      "login": "26784951",
      "slug": "dutchs",
      "image": {
        "50": "https://static-cdn.jtvnw.net/user-default-pictures/cd618d3e-f14d-4960-b7cf-094231b04735-profile_image-50x50.jpg",
        "70": "https://static-cdn.jtvnw.net/user-default-pictures/cd618d3e-f14d-4960-b7cf-094231b04735-profile_image-70x70.jpg",
        "150": "https://static-cdn.jtvnw.net/user-default-pictures/cd618d3e-f14d-4960-b7cf-094231b04735-profile_image-150x150.jpg",
        "300": "https://static-cdn.jtvnw.net/user-default-pictures/cd618d3e-f14d-4960-b7cf-094231b04735-profile_image-300x300.jpg"
      },
      "type": "twitch",
      "id": 2,
      "favorites": []
    }
  ],
  "prefs": {
    "queue": {
      "interval": 60,
      "requests": 4,
      "maxRetries": 5
    },
    "panel": {
      "style": "0",
      "extras": true,
      "badge": true
    },
    "misc": {
      "cacheTime": 600000,
      "findMature": true
    }
  },
  "meta": {
    "version": "3.10.3",
    "platform": "win",
    "platformArch": "x86-64",
    "language": "en-US",
    "lastError": null
  }
}
```

## Additional debug info
Console Output:
[Debug_Console.txt](https://github.com/freaktechnik/justintv-stream-notifications/files/2707754/Debug_Console.txt)
Network Requests:
![debug_network](https://user-images.githubusercontent.com/1423624/50406720-0595c380-07ca-11e9-871b-019c8c19174c.png)

**Comment by freaktechnik** [comment]
This will be fixed in 3.10.4 Thank you again for the report and sorry for the broken experience.
