### ISSUE TITLE
[Feature Request] Notification for changed category

### ISSUE THREAD

**Issue by BubiBalboa** [freaktechnik/justintv-stream-notifications#466]
Would it be possible to include a setting to allow for notifications when a (Twitch) stream changes the category?

I found this to be a much more reliable indicator of changed content than the stream title, which is changed less frequently in my experience. 

Even better would be conditional notifications like `if streamer X plays game Y` but I think your are already working on something like that with the [Action Editor](https://github.com/freaktechnik/justintv-stream-notifications/issues/433), yes? 

I just found your extension and am very impressed. Thanks for your great work!

**Comment by freaktechnik** [comment]
This will be possible as part of #382 which is wrongly named at this point - but it's essentially the flexibility of actions for notifications. I'll close it as duplicate for now.

**Comment by BubiBalboa** [comment]
Perfect! Thanks
