### ISSUE TITLE
javascript:openTab is not defined

### ISSUE THREAD

**Issue by HerptyDerpoty** [freaktechnik/justintv-stream-notifications#61]
SO everything about this works, it eventuallys auto finds my username and sees all my followed streamers, but javascript:openTab doesnt work, i even tried entering the command your plugin calls into the webdev console
javascript:opentab("destiny","twitch") and got
[00:08:39.015] ReferenceError: opentab is not defined
i have the latest version of java 7 (45) and firefox 24.
this means you cant click the streamers box in the dropdown list and have it open there stream.

**Comment by freaktechnik** [comment]
Closing this, as it can't happen in the same way with 3.0.1
