### ISSUE TITLE
Viagame provider

### ISSUE THREAD

**Issue by freaktechnik** [freaktechnik/justintv-stream-notifications#77]

**Comment by freaktechnik** [comment]
I'm not sure viagame still does actual livestreams, I think they switched to VODs only.

**Comment by vasklund** [comment]
Yup, all our streams are on Twitch/YouTube/Hitbox for now :)

**Comment by freaktechnik** [comment]
@vasklund thanks for the confirmation. I noticed you're using a branded hitbox stream for your "own" stream for the house cup 3.
